[package]
name = "tusdt-governance"
version = "0.1.0"
authors = ["tensorusd admin@tensorusd.com"]
edition = "2021"

[dependencies]
ink = { workspace = true, default-features = false }
tusdt-env = { path = "../../env", default-features = false }
tusdt-treasury = { path = "../tusdt-treasury", default-features = false, features = [
    "ink-as-dependency",
] }
tusdt-vault-alpha = { path = "../tusdt-vault-alpha", default-features = false, features = [
    "ink-as-dependency",
] }
tusdt-auction = { path = "../tusdt-auction", default-features = false, features = [
    "ink-as-dependency",
] }
tusdt-oracle = { path = "../tusdt-oracle", default-features = false, features = [
    "ink-as-dependency",
] }
tusdt-election = { path = "../tusdt-election", default-features = false, features = [
    "ink-as-dependency",
] }
tusdt-lending-pool = { path = "../tusdt-lending-pool", default-features = false, features = ["ink-as-dependency"] }
tusdt-primitives = { path = "../../primitives", default-features = false }
tusdt-voting = { path = "../../voting", default-features = false }

[dev-dependencies]
ink_e2e = { workspace = true }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "tusdt-env/std",
    "tusdt-treasury/std",
    "tusdt-vault-alpha/std",
    "tusdt-auction/std",
    "tusdt-oracle/std",
    "tusdt-election/std",
    "tusdt-lending-pool/std",
    "tusdt-primitives/std",
    "tusdt-voting/std",
]
ink-as-dependency = []
e2e-tests = []
